#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/

image: mcr.microsoft.com/dotnet/sdk:6.0

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - dotnetcore
        script:
          # NOTE: zip isn't installed in the image, so we must manually add it
          - apt-get update
          - apt-get install zip -y
          - dotnet restore
          - dotnet build
          - dotnet test
          - dotnet publish ./WebApp/WebApp.csproj -c Release -o ./publish
          - cd ./publish
          - zip -r WebApp.zip .
          - mkdir –p $BITBUCKET_CLONE_DIR/dist
          - cp -R WebApp.zip $BITBUCKET_CLONE_DIR/dist
          - ls -lah $BITBUCKET_CLONE_DIR/dist
        artifacts:
          - dist/**
    - step:
        name: Deploy To S3
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:0.3.8
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: "ap-southeast-1"
              S3_BUCKET: "aws-s3-dev"
              LOCAL_PATH: "dist"
              ACL: "public-read"
